Repository Enet4/dicom-rs, pull requests merged in 2021-08, with the labels that each got.

#154 [dcmdump] clean all strings properly
  dcmdump/src/main.rs
Labels: C-tool

#149 [pixeldata] Fetch the first frame of native pixel data on decode_pixel_data
  pixeldata/src/gdcm.rs
  pixeldata/src/lib.rs
Labels: bug

#151 [pixeldata] reexport public dependencies
  pixeldata/src/lib.rs
Labels: C-lib

#158 [storescu] Orthanc PACS interoperability
  storescu/src/main.rs
  ul/src/association/client.rs
  ul/src/pdu/reader.rs
Labels: bug
