Repository Enet4/dicom-rs, pull requests merged in 2022-01, with the labels that each got.

#208 [dump] Fix set_virtual_terminal call on Windows
  .github/workflows/rust.yml
  dcmdump/src/main.rs
  dump/src/main.rs
Labels: bug, C-tool

#207 [dump] Enable dumping more than one file
  dump/src/main.rs
Labels: enhancement, C-tool

#202 Upgrade SNAFU to v0.7
  core/Cargo.toml
  core/src/dictionary/mod.rs
  core/src/header.rs
  core/src/value/deserialize.rs
  core/src/value/partial.rs
  core/src/value/primitive.rs
  core/src/value/range.rs
  dcmdump/Cargo.toml
  dump/Cargo.toml
  encoding/Cargo.toml
  encoding/src/adapters/rle_lossless.rs
  encoding/src/decode/explicit_be.rs
  encoding/src/decode/explicit_le.rs
  encoding/src/decode/implicit_le.rs
  encoding/src/encode/explicit_be.rs
  encoding/src/encode/explicit_le.rs
  encoding/src/encode/implicit_le.rs
  encoding/src/encode/mod.rs
  encoding/src/text.rs
  object/Cargo.toml
  object/src/lib.rs
  object/src/mem.rs
  object/src/meta.rs
  object/src/pixeldata.rs
  parser/Cargo.toml
  parser/src/dataset/lazy_read.rs
  parser/src/dataset/mod.rs
  parser/src/dataset/read.rs
  parser/src/dataset/write.rs
  parser/src/stateful/decode.rs
  parser/src/stateful/encode.rs
  pixeldata/Cargo.toml
  pixeldata/src/gdcm.rs
  pixeldata/src/lib.rs
  scpproxy/Cargo.toml
  scpproxy/src/main.rs
  ul/Cargo.toml
  ul/src/association/client.rs
  ul/src/association/server.rs
  ul/src/pdu/reader.rs
  ul/src/pdu/writer.rs
Labels: breaking change, C-lib

#214 [core] Admit second-precise times to be converted to a chrono NaiveTime
  core/src/value/deserialize.rs
  core/src/value/primitive.rs
  core/src/value/range.rs
  dump/src/lib.rs
Labels: C-lib, C-tool

#211 [storescu] Enable sending more than one file
  storescu/Cargo.toml
  storescu/src/main.rs
Labels: C-tool
