Repository Enet4/dicom-rs, pull requests merged in 2022-10, with the labels that each got.

#280 [object] Make it possible to mutate FileMetaTable in FileDicomObject
  object/src/lib.rs
  object/src/mem.rs
  object/src/meta.rs
Labels: enhancement, C-lib

#290 [ul|object] update implementation UID and version name
  object/src/lib.rs
  object/src/meta.rs
  ul/src/lib.rs
Labels: chore

#289 Clippy maintenance
  core/src/lib.rs
  core/src/value/person_name.rs
  core/src/value/range.rs
  dump/src/lib.rs
  encoding/src/decode/basic.rs
  encoding/src/lib.rs
  object/src/lib.rs
  parser/src/lib.rs
  pixeldata/src/lib.rs
  storescu/src/main.rs
Labels: chore

#288 [core] Add tag parsing implementation
  core/src/header.rs
Labels: enhancement, C-lib

#284 [ul] address module
  echoscu/Cargo.toml
  echoscu/src/main.rs
  storescu/Cargo.toml
  storescu/src/main.rs
  ul/src/address.rs
  ul/src/association/client.rs
  ul/src/lib.rs
Labels: enhancement, C-lib, C-tool

#291 [ul] Improve association robustness and expressiveness
  ul/src/association/client.rs
  ul/src/association/mod.rs
  ul/src/association/server.rs
  ul/src/association/uid.rs
  ul/src/pdu/mod.rs
  ul/tests/association_store.rs
Labels: bug, enhancement, C-lib

#295 [transfer-syntax-registry] add TransferSyntaxRegistry::iter
  transfer-syntax-registry/src/lib.rs
Labels: enhancement, C-lib

#292 [object] Add getter methods to FileMetaTable
  object/src/meta.rs
Labels: enhancement, C-lib

#298 [core] Fix swapped variant documentation
  core/src/header.rs
Labels: bug, C-lib

#299 - fix person_name whitespace trim
  core/src/value/person_name.rs
Labels: bug, C-lib

#297 Use snafu report API in CLI tools
  core/Cargo.toml
  dump/Cargo.toml
  dump/src/main.rs
  echoscu/Cargo.toml
  echoscu/src/main.rs
  encoding/Cargo.toml
  fromimage/Cargo.toml
  fromimage/src/main.rs
  object/Cargo.toml
  parser/Cargo.toml
  pixeldata/Cargo.toml
  scpproxy/Cargo.toml
  scpproxy/src/main.rs
  storescu/Cargo.toml
  storescu/src/main.rs
  toimage/Cargo.toml
  toimage/src/main.rs
  ul/Cargo.toml
Labels: enhancement, C-lib, C-tool

#300 [dump] Add utility functions dump_object and dump_object_to
  dump/src/lib.rs
Labels: enhancement, C-lib

#301 [ul] minor improvements to *AeAddr types
  ul/src/address.rs
Labels: enhancement, C-lib

#296 [storescp] First implementation of a Store SCP
  Cargo.toml
  README.md
  echoscu/src/main.rs
  storescp/Cargo.toml
  storescp/README.md
  storescp/src/main.rs
  storescp/src/transfer.rs
Labels: C-tool

#144 Find SCU
  Cargo.toml
  README.md
  findscu/Cargo.toml
  findscu/README.md
  findscu/src/main.rs
  findscu/src/query.rs
Labels: C-tool
